apiVersion: v1
kind: Secret
metadata:
  name: gitops-private-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:mehedi-iut/<repo name>.git
  sshPrivateKey: |


  insecure: "false"
  enableLfs: "true"
